name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "<%= package.version %>"
include = ["./tomls/proxy-base.toml"]
include = ["./tomls/council-token.toml"]

[setting.salt]
defaultValue = "governance"

# Deployment Owner, defaults to first hardhat account
[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.minimum_active_members]
defaultValue = "1"

[setting.initial_nomination_period_start_date]
defaultValue = "0" # defaults to "block.timestamp + administration_period_duration" when given "0"

[setting.administration_period_duration]
defaultValue = "60" # days

[setting.nomination_period_duration]
defaultValue = "15" # days

[setting.voting_period_duration]
defaultValue = "15" # days

[contract.AssociatedSystemsModule]
artifact = "contracts/modules/core/AssociatedSystemsModule.sol:AssociatedSystemsModule"

[contract.CrossChainModule]
artifact = "contracts/modules/core/CrossChainModule.sol:CrossChainModule"

[contract.ElectionInspectorModule]
artifact = "contracts/modules/core/ElectionInspectorModule.sol:ElectionInspectorModule"

[contract.ElectionModule]
artifact = "contracts/modules/core/ElectionModule.sol:ElectionModule"

[contract.SnapshotVotePowerModule]
artifact = "contracts/modules/core/SnapshotVotePowerModule.sol:SnapshotVotePowerModule"

[contract.CouncilTokenModule]
artifact = "contracts/modules/council-nft/CouncilTokenModule.sol:CouncilTokenModule"

[router.CoreRouter]
contracts = [
    "AssociatedSystemsModule",
    "CrossChainModule",
    "ElectionInspectorModule",
    "ElectionModule",
    "SnapshotVotePowerModule",
    "InitialModuleBundle",
]

[invoke.upgrade_core_proxy]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]
factory.CoreProxy.abiOf = ["CoreRouter"]
factory.CoreProxy.event = "Upgraded"
factory.CoreProxy.arg = 0
depends = ["contract.InitialProxy", "router.CoreRouter"]

[invoke.init_election_module]
target = ["CoreProxy"]
func = "initOrUpdateElectionSettings(address[],uint8,uint64,uint64,uint64,uint64)"
args = [
    ["<%= settings.init_council_member %>"],
    "<%= settings.minimum_active_members %>",
    "<%= settings.initial_nomination_period_start_date %>",
    "<%= settings.administration_period_duration %>",
    "<%= settings.nomination_period_duration %>",
    "<%= settings.voting_period_duration %>",
]
from = "<%= settings.owner %>"
