name = "synthetix-governance"
description = "On-chain voting for synthetix councils - Logic for satellite chains"
version = "<%= package.version %>"
include = [
    "./tomls/proxy-base.toml",
    "./tomls/council-token.toml",
    "./tomls/ccip.toml",
]

[setting.initial_epoch_index]
defaultValue = "0"

[contract.AssociatedSystemsModule]
artifact = "contracts/modules/core/AssociatedSystemsModule.sol:AssociatedSystemsModule"

[contract.CrossChainModule]
artifact = "contracts/modules/core/CrossChainModule.sol:CrossChainModule"

[contract.ElectionModuleSatellite]
artifact = "contracts/modules/core/ElectionModuleSatellite.sol:ElectionModuleSatellite"

[contract.CouncilTokenModule]
artifact = "contracts/modules/council-nft/CouncilTokenModule.sol:CouncilTokenModule"

[router.CoreRouter]
contracts = [
    "AssociatedSystemsModule",
    "CrossChainModule",
    "ElectionModuleSatellite",
    "InitialModuleBundle",
]
depends = [
    "contract.AssociatedSystemsModule",
    "contract.CrossChainModule",
    "contract.ElectionModuleSatellite",
    "contract.InitialModuleBundle",
]

[invoke.upgrade_core_proxy]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]
factory.CoreProxy.abiOf = ["CoreRouter"]
factory.CoreProxy.event = "Upgraded"
factory.CoreProxy.arg = 0
depends = ["contract.InitialProxy", "router.CoreRouter"]

[invoke.init_election_module_satellite]
target = ["CoreProxy"]
func = "initCouncilMembers"
from = "<%= settings.owner %>"
args = [
    ["<%= settings.initial_council_member %>"],
    "<%= settings.initial_epoch_index %>",
]
depends = ["invoke.upgrade_core_proxy"]
