name = "synthetix-governance-satellite"
description = "On-chain voting for synthetix councils - Logic for satellite chains"
version = "<%= package.version %>"
include = ["./tomls/proxy-base.toml", "./tomls/council-token.toml"]

# Override this value in the CLI, default value is for Sepolia
[setting.ccip_router]
defaultValue = "0xd0daae2231e9cb96b94c8512223533293c3693bf"

# Deployment Owner, defaults to first hardhat account
[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.initial_epoch_index]
defaultValue = "0"

[setting.initial_council_member]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[contract.AssociatedSystemsModule]
artifact = "contracts/modules/core/AssociatedSystemsModule.sol:AssociatedSystemsModule"

[contract.CrossChainModule]
artifact = "contracts/modules/core/CrossChainModule.sol:CrossChainModule"

[contract.ElectionModuleSatellite]
artifact = "contracts/modules/core/ElectionModuleSatellite.sol:ElectionModuleSatellite"

[contract.CouncilTokenModule]
artifact = "contracts/modules/council-nft/CouncilTokenModule.sol:CouncilTokenModule"

[router.CoreRouter]
contracts = [
    "AssociatedSystemsModule",
    "CrossChainModule",
    "ElectionModuleSatellite",
    "InitialModuleBundle",
]
depends = [
    "contract.AssociatedSystemsModule",
    "contract.CrossChainModule",
    "contract.ElectionModuleSatellite",
    "contract.InitialModuleBundle",
]

[invoke.upgrade_core_proxy]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]
factory.CoreProxy.abiOf = ["CoreRouter"]
factory.CoreProxy.event = "Upgraded"
factory.CoreProxy.arg = 0
depends = ["contract.InitialProxy", "router.CoreRouter"]

[invoke.init_election_module_satellite]
target = ["CoreProxy"]
func = "initCouncilMembers"
from = "<%= settings.owner %>"
args = [
    ["<%= settings.initial_council_member %>"],
    "<%= settings.initial_epoch_index %>",
]
depends = ["invoke.upgrade_core_proxy"]

[invoke.set_supported_cross_chain_networks]
target = ["CoreProxy"]
fromCall.func = "owner"
func = "setSupportedCrossChainNetworks"
args = [
    ["11155111", "420", "421613", "80001", "84531"],
    [
        "16015286601757825753",
        "2664363617261496610",
        "6101244977088475029",
        "12532609583862916517",
        "5790810961207155433"
    ]
]
depends = ["invoke.init_election_module_satellite"]

[invoke.configure_chainlink_cross_chain]
target = ["CoreProxy"]
func = "configureChainlinkCrossChain"
from = "<%= settings.owner %>"
args = ["<%= settings.ccip_router %>"]
depends = ["invoke.set_supported_cross_chain_networks"]
