name = "synthetix-governance-satellite"
description = "On-chain voting for synthetix councils - Logic for satellite chains"
version = "<%= package.version %>"
include = ["./tomls/proxy-base.toml"]
include = ["./tomls/council-token.toml"]

[setting.salt]
defaultValue = "governance-satellite"

# Deployment Owner, defaults to first hardhat account
[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[contract.AssociatedSystemsModule]
artifact = "contracts/modules/core/AssociatedSystemsModule.sol:AssociatedSystemsModule"

[contract.CrossChainModule]
artifact = "contracts/modules/core/CrossChainModule.sol:CrossChainModule"

[contract.ElectionModuleSatellite]
artifact = "contracts/modules/core/ElectionModuleSatellite.sol:ElectionModuleSatellite"

[contract.CouncilTokenModule]
artifact = "contracts/modules/council-nft/CouncilTokenModule.sol:CouncilTokenModule"

[router.CoreRouter]
contracts = [
    "AssociatedSystemsModule",
    "CrossChainModule",
    "ElectionModuleSatellite",
    "InitialModuleBundle",
]

[invoke.upgrade_core_proxy]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]
factory.CoreProxy.abiOf = ["CoreRouter"]
factory.CoreProxy.event = "Upgraded"
factory.CoreProxy.arg = 0
